# Baseline Installation Properties
openboard = Interactive whiteboard for schools and universities
git = Distributed version control system for tracking code changes
vscode = Extensible, lightweight source-code editor developed by Microsoft
