# Chemistry Module Installation Properties
avogadro = Avogadro (Molecular Editor and Modeling)
kalzium = Advanced Interactive Periodic Table (Kalzium)
chemtool = Chemtool (Chemical Structure Drawing Program)
